name: notes_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-150.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_sliders: ^19.4.55
  font_awesome_flutter: ^9.2.0
  connectivity_plus: ^2.2.1
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.5
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Redressed
      fonts:
        - asset: fonts/Redressed-Regular.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Josefin Sans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf